#!/bin/bash
# Signaler Repository Cleanup Script
# This script removes redundant files and prepares for release

set -e

echo "🧹 Signaler Repository Cleanup"
echo "================================"
echo ""

# Confirm before proceeding
read -p "This will remove redundant files. Continue? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Cleanup cancelled."
    exit 1
fi

echo ""
echo "📦 Phase 1: Removing redundant files..."

# Remove simplified version files
if [ -d "src-simplified" ]; then
    echo "  ❌ Removing src-simplified/"
    rm -rf src-simplified/
fi

if [ -d "dist-simplified" ]; then
    echo "  ❌ Removing dist-simplified/"
    rm -rf dist-simplified/
fi

if [ -f "package.simplified.json" ]; then
    echo "  ❌ Removing package.simplified.json"
    rm package.simplified.json
fi

if [ -f "tsconfig.simplified.json" ]; then
    echo "  ❌ Removing tsconfig.simplified.json"
    rm tsconfig.simplified.json
fi

if [ -f "README.simplified.md" ]; then
    echo "  ❌ Removing README.simplified.md"
    rm README.simplified.md
fi

# Remove temporary documentation
if [ -f "FULL-VERSION-READY.md" ]; then
    echo "  ❌ Removing FULL-VERSION-READY.md"
    rm FULL-VERSION-READY.md
fi

# Remove test artifacts (will be added to .gitignore)
if [ -d "test-report" ]; then
    echo "  ❌ Removing test-report/"
    rm -rf test-report/
fi

if [ -d "test-report-failed" ]; then
    echo "  ❌ Removing test-report-failed/"
    rm -rf test-report-failed/
fi

if [ -d "signaler-report" ]; then
    echo "  ❌ Removing signaler-report/"
    rm -rf signaler-report/
fi

if [ -f "apex.config.json" ]; then
    echo "  ❌ Removing apex.config.json (test artifact)"
    rm apex.config.json
fi

# Remove release artifacts (generated by CI)
if [ -d "release" ]; then
    echo "  ❌ Removing release/ (will be generated by CI)"
    rm -rf release/
fi

echo ""
echo "✅ Phase 1 complete!"
echo ""
echo "📝 Phase 2: Updating .gitignore..."

# Backup existing .gitignore
if [ -f ".gitignore" ]; then
    cp .gitignore .gitignore.backup
    echo "  💾 Backed up .gitignore to .gitignore.backup"
fi

# Add entries to .gitignore
cat >> .gitignore << 'EOF'

# Build outputs
dist/
dist-simplified/
*.tgz

# Test artifacts
test-report/
test-report-failed/
signaler-report/
apex.config.json
.signaler/

# Release artifacts
release/
*.zip

# Rust build artifacts
launcher/target/

# Node modules
node_modules/
app/node_modules/

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db

# Logs
*.log
npm-debug.log*
pnpm-debug.log*

# Environment
.env
.env.local
EOF

echo "  ✅ Updated .gitignore"
echo ""
echo "✅ Phase 2 complete!"
echo ""
echo "🎉 Cleanup finished!"
echo ""
echo "Next steps:"
echo "  1. Review changes: git status"
echo "  2. Update package.json (remove simplified references)"
echo "  3. Update GitHub workflows (add Rust support)"
echo "  4. Test build: pnpm build"
echo "  5. Test Rust launcher: cd launcher && cargo build --release"
echo "  6. Commit changes: git add . && git commit -m 'chore: cleanup redundant files'"
echo ""
echo "See CLEANUP-AND-RELEASE-PLAN.md for full details."
