export type ShellCommandId =
  | "install"
  | "run"
  | "review"
  | "audit"
  | "quick"
  | "report"
  | "analyze"
  | "verify"
  | "query"
  | "explain"
  | "job"
  | "upgrade"
  | "measure"
  | "bundle"
  | "folder"
  | "health"
  | "links"
  | "headers"
  | "console"
  | "accessibility"
  | "clean"
  | "uninstall"
  | "clear-screenshots"
  | "wizard"
  | "quickstart"
  | "guide"
  | "tui"
  | "shell"
  | "help"
  | "init"
  | "discover"
  | "config"
  | "export"
  | "ai"
  | "cortex"
  | "auth"
  | "version"
  | "install-shim";

export interface ParsedShellArgs {
  readonly command: ShellCommandId;
  readonly argv: readonly string[];
}
