/**
 * HTML Report Generator - Interactive user-friendly HTML reports
 * 
 * This module generates responsive, interactive HTML reports optimized for
 * non-technical users with visual performance metrics and issue exploration.
 */

import type { ProcessedAuditData, PageAuditResult, Issue, Opportunity } from './report-generator-engine.js';

export interface HTMLReportConfig {
  includeCharts: boolean;
  enableFiltering: boolean;
  enableSorting: boolean;
  mobileOptimized: boolean;
  theme: 'light' | 'dark' | 'auto';
}

export interface ChartData {
  labels: string[];
  datasets: ChartDataset[];
}

export interface ChartDataset {
  label: string;
  data: number[];
  backgroundColor: string[];
  borderColor: string[];
}

export interface FilterOptions {
  severityLevels: string[];
  categories: string[];
  scoreRanges: ScoreRange[];
}

export interface ScoreRange {
  min: number;
  max: number;
  label: string;
}

/**
 * Generates interactive HTML reports with charts and filtering
 */
export class HTMLReportGenerator {
  private config: HTMLReportConfig;

  constructor(config: HTMLReportConfig = {
    includeCharts: true,
    enableFiltering: true,
    enableSorting: true,
    mobileOptimized: true,
    theme: 'auto'
  }) {
    this.config = config;
  }

  /**
   * Generate complete HTML report
   */
  async generateReport(data: ProcessedAuditData): Promise<string> {
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  ${this.generateHead()}
</head>
<body class="theme-${this.config.theme}">
  ${this.generateHeader(data)}
  ${this.generateNavigation()}
  
  <main class="main-content">
    ${this.generatePerformanceOverview(data)}
    ${this.config.includeCharts ? this.generateChartsSection(data) : ''}
    ${this.generatePagesSection(data)}
    ${this.generateIssuesSection(data)}
    ${this.generateOpportunitiesSection(data)}
  </main>
  
  ${this.generateFooter(data)}
  ${this.generateScripts()}
</body>
</html>`;

    return html;
  }

  /**
   * Generate HTML head section with styles and meta tags
   */
  private generateHead(): string {
    return `
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Signaler Performance Report</title>
  <meta name="description" content="Interactive web performance audit report generated by Signaler">
  
  <!-- Chart.js for interactive charts -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.js"></script>
  
  <!-- Custom styles -->
  <style>
    ${this.generateCSS()}
  </style>`;
  }

  /**
   * Generate comprehensive CSS styles
   */
  private generateCSS(): string {
    return `
    /* Reset and base styles */
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    :root {
      --primary-color: #2563eb;
      --success-color: #16a34a;
      --warning-color: #d97706;
      --error-color: #dc2626;
      --critical-color: #991b1b;
      --background-color: #ffffff;
      --surface-color: #f8fafc;
      --text-primary: #1e293b;
      --text-secondary: #64748b;
      --border-color: #e2e8f0;
      --shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1);
      --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1);
    }

    .theme-dark {
      --background-color: #0f172a;
      --surface-color: #1e293b;
      --text-primary: #f1f5f9;
      --text-secondary: #94a3b8;
      --border-color: #334155;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: var(--text-primary);
      background-color: var(--background-color);
    }

    /* Layout */
    .header {
      background: var(--surface-color);
      border-bottom: 1px solid var(--border-color);
      padding: 1rem 0;
      position: sticky;
      top: 0;
      z-index: 100;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 0 1rem;
    }

    .navigation {
      background: var(--primary-color);
      color: white;
      padding: 0.5rem 0;
    }

    .nav-links {
      display: flex;
      gap: 2rem;
      list-style: none;
    }

    .nav-links a {
      color: white;
      text-decoration: none;
      padding: 0.5rem 1rem;
      border-radius: 0.25rem;
      transition: background-color 0.2s;
    }

    .nav-links a:hover {
      background-color: rgba(255, 255, 255, 0.1);
    }

    .main-content {
      padding: 2rem 0;
    }

    /* Cards and sections */
    .section {
      margin-bottom: 3rem;
    }

    .section-title {
      font-size: 1.875rem;
      font-weight: 700;
      margin-bottom: 1rem;
      color: var(--text-primary);
    }

    .card {
      background: var(--surface-color);
      border: 1px solid var(--border-color);
      border-radius: 0.5rem;
      padding: 1.5rem;
      box-shadow: var(--shadow);
      margin-bottom: 1rem;
    }

    .card-title {
      font-size: 1.25rem;
      font-weight: 600;
      margin-bottom: 0.5rem;
    }

    /* Performance metrics */
    .metrics-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 1rem;
      margin-bottom: 2rem;
    }

    .metric-card {
      text-align: center;
      padding: 1.5rem;
    }

    .metric-value {
      font-size: 2.5rem;
      font-weight: 700;
      margin-bottom: 0.5rem;
    }

    .metric-label {
      color: var(--text-secondary);
      font-size: 0.875rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    /* Score indicators */
    .score {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 3rem;
      height: 3rem;
      border-radius: 50%;
      font-weight: 700;
      color: white;
    }

    .score-excellent { background-color: var(--success-color); }
    .score-good { background-color: #22c55e; }
    .score-needs-improvement { background-color: var(--warning-color); }
    .score-poor { background-color: var(--error-color); }

    /* Severity indicators */
    .severity {
      display: inline-block;
      padding: 0.25rem 0.75rem;
      border-radius: 9999px;
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: uppercase;
    }

    .severity-critical {
      background-color: var(--critical-color);
      color: white;
    }

    .severity-high {
      background-color: var(--error-color);
      color: white;
    }

    .severity-medium {
      background-color: var(--warning-color);
      color: white;
    }

    .severity-low {
      background-color: var(--success-color);
      color: white;
    }

    /* Tables */
    .table-container {
      overflow-x: auto;
      border-radius: 0.5rem;
      border: 1px solid var(--border-color);
    }

    .table {
      width: 100%;
      border-collapse: collapse;
      background: var(--surface-color);
    }

    .table th,
    .table td {
      padding: 0.75rem 1rem;
      text-align: left;
      border-bottom: 1px solid var(--border-color);
    }

    .table th {
      background: var(--background-color);
      font-weight: 600;
      color: var(--text-primary);
    }

    .table tbody tr:hover {
      background-color: rgba(59, 130, 246, 0.05);
    }

    /* Filters and controls */
    .controls {
      display: flex;
      flex-wrap: wrap;
      gap: 1rem;
      margin-bottom: 1.5rem;
      padding: 1rem;
      background: var(--surface-color);
      border-radius: 0.5rem;
      border: 1px solid var(--border-color);
    }

    .filter-group {
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }

    .filter-label {
      font-size: 0.875rem;
      font-weight: 600;
      color: var(--text-secondary);
    }

    .filter-select,
    .filter-input {
      padding: 0.5rem;
      border: 1px solid var(--border-color);
      border-radius: 0.25rem;
      background: var(--background-color);
      color: var(--text-primary);
    }

    .btn {
      padding: 0.5rem 1rem;
      border: none;
      border-radius: 0.25rem;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.2s;
    }

    .btn-primary {
      background: var(--primary-color);
      color: white;
    }

    .btn-primary:hover {
      background: #1d4ed8;
    }

    /* Charts */
    .chart-container {
      position: relative;
      height: 400px;
      margin-bottom: 2rem;
    }

    .charts-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
      gap: 2rem;
      margin-bottom: 2rem;
    }

    /* Issue explorer */
    .issue-item {
      border-left: 4px solid var(--border-color);
      padding: 1rem;
      margin-bottom: 1rem;
      background: var(--surface-color);
      border-radius: 0 0.25rem 0.25rem 0;
    }

    .issue-item.critical { border-left-color: var(--critical-color); }
    .issue-item.high { border-left-color: var(--error-color); }
    .issue-item.medium { border-left-color: var(--warning-color); }
    .issue-item.low { border-left-color: var(--success-color); }

    .issue-header {
      display: flex;
      justify-content: between;
      align-items: center;
      margin-bottom: 0.5rem;
    }

    .issue-title {
      font-weight: 600;
      margin-right: 1rem;
    }

    .issue-savings {
      font-size: 0.875rem;
      color: var(--text-secondary);
    }

    .code-example {
      background: #1e293b;
      color: #e2e8f0;
      padding: 1rem;
      border-radius: 0.25rem;
      font-family: 'Monaco', 'Menlo', monospace;
      font-size: 0.875rem;
      overflow-x: auto;
      margin: 1rem 0;
    }

    /* Responsive design */
    @media (max-width: 768px) {
      .container {
        padding: 0 0.5rem;
      }

      .nav-links {
        flex-direction: column;
        gap: 0.5rem;
      }

      .metrics-grid {
        grid-template-columns: 1fr;
      }

      .charts-grid {
        grid-template-columns: 1fr;
      }

      .controls {
        flex-direction: column;
      }

      .chart-container {
        height: 300px;
      }
    }

    /* Accessibility */
    @media (prefers-reduced-motion: reduce) {
      * {
        animation-duration: 0.01ms !important;
        animation-iteration-count: 1 !important;
        transition-duration: 0.01ms !important;
      }
    }

    /* Focus styles */
    .btn:focus,
    .filter-select:focus,
    .filter-input:focus {
      outline: 2px solid var(--primary-color);
      outline-offset: 2px;
    }

    /* Loading states */
    .loading {
      opacity: 0.6;
      pointer-events: none;
    }

    .spinner {
      border: 2px solid var(--border-color);
      border-top: 2px solid var(--primary-color);
      border-radius: 50%;
      width: 1rem;
      height: 1rem;
      animation: spin 1s linear infinite;
    }

    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
    `;
  }

  /**
   * Generate header section
   */
  private generateHeader(data: ProcessedAuditData): string {
    const auditDate = new Date(data.auditMetadata.completedAt).toLocaleDateString();
    const auditTime = new Date(data.auditMetadata.completedAt).toLocaleTimeString();
    
    return `
  <header class="header">
    <div class="container">
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <div>
          <h1 style="font-size: 2rem; font-weight: 700; margin-bottom: 0.25rem;">
            Signaler Performance Report
          </h1>
          <p style="color: var(--text-secondary);">
            Generated on ${auditDate} at ${auditTime}
          </p>
        </div>
        <div style="text-align: right;">
          <div style="font-size: 1.25rem; font-weight: 600;">
            ${data.performanceMetrics.totalPages} Pages Audited
          </div>
          <div style="color: var(--text-secondary); font-size: 0.875rem;">
            in ${Math.round(data.auditMetadata.elapsedMs / 1000)}s
          </div>
        </div>
      </div>
    </div>
  </header>`;
  }

  /**
   * Generate navigation menu
   */
  private generateNavigation(): string {
    return `
  <nav class="navigation">
    <div class="container">
      <ul class="nav-links">
        <li><a href="#overview">Overview</a></li>
        <li><a href="#charts">Performance Charts</a></li>
        <li><a href="#pages">Page Details</a></li>
        <li><a href="#issues">Issues</a></li>
        <li><a href="#opportunities">Opportunities</a></li>
      </ul>
    </div>
  </nav>`;
  }

  /**
   * Generate performance overview section
   */
  private generatePerformanceOverview(data: ProcessedAuditData): string {
    const { performanceMetrics } = data;
    const scoreClass = this.getScoreClass(performanceMetrics.averagePerformanceScore);
    
    return `
  <section id="overview" class="section">
    <div class="container">
      <h2 class="section-title">Performance Overview</h2>
      
      <div class="card" style="background: linear-gradient(135deg, var(--primary-color), #3b82f6); color: white; margin-bottom: 2rem;">
        <div style="text-align: center;">
          <div style="font-size: 0.875rem; opacity: 0.9; margin-bottom: 0.5rem;">
            ⚠️ Performance scores are typically lower in automated testing environments compared to manual DevTools testing
          </div>
          <div style="font-size: 0.75rem; opacity: 0.8;">
            Focus on relative improvements and specific optimization opportunities rather than absolute scores
          </div>
        </div>
      </div>
      
      <div class="metrics-grid">
        <div class="card metric-card">
          <div class="metric-value score ${scoreClass}">
            ${performanceMetrics.averagePerformanceScore}
          </div>
          <div class="metric-label">Average Performance Score</div>
        </div>
        
        <div class="card metric-card">
          <div class="metric-value" style="color: var(--text-primary);">
            ${performanceMetrics.totalPages}
          </div>
          <div class="metric-label">Total Pages Audited</div>
        </div>
        
        <div class="card metric-card">
          <div class="metric-value" style="color: var(--error-color);">
            ${performanceMetrics.criticalIssuesCount}
          </div>
          <div class="metric-label">Critical Issues</div>
        </div>
        
        <div class="card metric-card">
          <div class="metric-value" style="color: var(--success-color);">
            ${Math.round(performanceMetrics.estimatedTotalSavings / 1000)}s
          </div>
          <div class="metric-label">Potential Time Savings</div>
        </div>
      </div>
    </div>
  </section>`;
  }

  /**
   * Generate charts section
   */
  private generateChartsSection(data: ProcessedAuditData): string {
    if (!this.config.includeCharts) return '';

    return `
  <section id="charts" class="section">
    <div class="container">
      <h2 class="section-title">Performance Charts</h2>
      
      <div class="charts-grid">
        <div class="card">
          <h3 class="card-title">Performance Score Distribution</h3>
          <div class="chart-container">
            <canvas id="scoreDistributionChart"></canvas>
          </div>
        </div>
        
        <div class="card">
          <h3 class="card-title">Issues by Severity</h3>
          <div class="chart-container">
            <canvas id="issuesSeverityChart"></canvas>
          </div>
        </div>
        
        <div class="card">
          <h3 class="card-title">Performance Metrics Comparison</h3>
          <div class="chart-container">
            <canvas id="metricsComparisonChart"></canvas>
          </div>
        </div>
        
        <div class="card">
          <h3 class="card-title">Optimization Opportunities</h3>
          <div class="chart-container">
            <canvas id="opportunitiesChart"></canvas>
          </div>
        </div>
      </div>
    </div>
  </section>`;
  }

  /**
   * Generate pages section with filtering and sorting
   */
  private generatePagesSection(data: ProcessedAuditData): string {
    const filterControls = this.config.enableFiltering ? this.generateFilterControls() : '';
    
    return `
  <section id="pages" class="section">
    <div class="container">
      <h2 class="section-title">Page Performance Details</h2>
      
      ${filterControls}
      
      <div class="table-container">
        <table class="table" id="pagesTable">
          <thead>
            <tr>
              <th ${this.config.enableSorting ? 'class="sortable" data-sort="label"' : ''}>Page</th>
              <th ${this.config.enableSorting ? 'class="sortable" data-sort="performance"' : ''}>Performance</th>
              <th ${this.config.enableSorting ? 'class="sortable" data-sort="accessibility"' : ''}>Accessibility</th>
              <th ${this.config.enableSorting ? 'class="sortable" data-sort="bestPractices"' : ''}>Best Practices</th>
              <th ${this.config.enableSorting ? 'class="sortable" data-sort="seo"' : ''}>SEO</th>
              <th>Issues</th>
              <th>Device</th>
            </tr>
          </thead>
          <tbody>
            ${data.pages.map(page => this.generatePageRow(page)).join('')}
          </tbody>
        </table>
      </div>
    </div>
  </section>`;
  }

  /**
   * Generate filter controls
   */
  private generateFilterControls(): string {
    return `
  <div class="controls">
    <div class="filter-group">
      <label class="filter-label">Filter by Score Range</label>
      <select class="filter-select" id="scoreFilter">
        <option value="">All Scores</option>
        <option value="90-100">Excellent (90-100)</option>
        <option value="75-89">Good (75-89)</option>
        <option value="50-74">Needs Improvement (50-74)</option>
        <option value="0-49">Poor (0-49)</option>
      </select>
    </div>
    
    <div class="filter-group">
      <label class="filter-label">Filter by Device</label>
      <select class="filter-select" id="deviceFilter">
        <option value="">All Devices</option>
        <option value="desktop">Desktop</option>
        <option value="mobile">Mobile</option>
      </select>
    </div>
    
    <div class="filter-group">
      <label class="filter-label">Search Pages</label>
      <input type="text" class="filter-input" id="pageSearch" placeholder="Search by page name or path...">
    </div>
    
    <div class="filter-group">
      <button class="btn btn-primary" onclick="clearFilters()">Clear Filters</button>
    </div>
  </div>`;
  }

  /**
   * Generate individual page row
   */
  private generatePageRow(page: PageAuditResult): string {
    const issueCount = page.issues.length;
    const criticalIssues = page.issues.filter(issue => issue.severity === 'critical').length;
    
    return `
    <tr data-performance="${page.scores.performance}" data-device="${page.device}" data-label="${page.label.toLowerCase()}" data-path="${page.path.toLowerCase()}">
      <td>
        <div>
          <div style="font-weight: 600;">${this.escapeHtml(page.label)}</div>
          <div style="font-size: 0.875rem; color: var(--text-secondary);">${this.escapeHtml(page.path)}</div>
        </div>
      </td>
      <td>
        <div class="score ${this.getScoreClass(page.scores.performance)}">
          ${page.scores.performance}
        </div>
      </td>
      <td>
        <div class="score ${this.getScoreClass(page.scores.accessibility)}">
          ${page.scores.accessibility}
        </div>
      </td>
      <td>
        <div class="score ${this.getScoreClass(page.scores.bestPractices)}">
          ${page.scores.bestPractices}
        </div>
      </td>
      <td>
        <div class="score ${this.getScoreClass(page.scores.seo)}">
          ${page.scores.seo}
        </div>
      </td>
      <td>
        <div>
          <span style="font-weight: 600;">${issueCount}</span> total
          ${criticalIssues > 0 ? `<br><span style="color: var(--error-color);">${criticalIssues} critical</span>` : ''}
        </div>
      </td>
      <td>
        <span style="text-transform: capitalize;">${page.device}</span>
      </td>
    </tr>`;
  }

  /**
   * Generate issues section with interactive explorer
   */
  private generateIssuesSection(data: ProcessedAuditData): string {
    const allIssues = data.pages.flatMap(page => 
      page.issues.map(issue => ({ ...issue, pagePath: page.path, pageLabel: page.label }))
    );
    
    // Group issues by type for better organization
    const groupedIssues = this.groupIssuesByType(allIssues);
    
    return `
  <section id="issues" class="section">
    <div class="container">
      <h2 class="section-title">Performance Issues</h2>
      
      <div class="controls">
        <div class="filter-group">
          <label class="filter-label">Filter by Severity</label>
          <select class="filter-select" id="severityFilter">
            <option value="">All Severities</option>
            <option value="critical">Critical</option>
            <option value="high">High</option>
            <option value="medium">Medium</option>
            <option value="low">Low</option>
          </select>
        </div>
        
        <div class="filter-group">
          <label class="filter-label">Filter by Category</label>
          <select class="filter-select" id="categoryFilter">
            <option value="">All Categories</option>
            <option value="javascript">JavaScript</option>
            <option value="css">CSS</option>
            <option value="images">Images</option>
            <option value="caching">Caching</option>
            <option value="network">Network</option>
          </select>
        </div>
      </div>
      
      <div id="issuesContainer">
        ${Object.entries(groupedIssues).map(([type, issues]) => 
          this.generateIssueGroup(type, issues)
        ).join('')}
      </div>
    </div>
  </section>`;
  }

  /**
   * Generate opportunities section
   */
  private generateOpportunitiesSection(data: ProcessedAuditData): string {
    const allOpportunities = data.pages.flatMap(page => 
      page.opportunities.map(opp => ({ ...opp, pagePath: page.path, pageLabel: page.label }))
    );
    
    return `
  <section id="opportunities" class="section">
    <div class="container">
      <h2 class="section-title">Optimization Opportunities</h2>
      
      <div class="card">
        <p style="margin-bottom: 1rem; color: var(--text-secondary);">
          These opportunities represent potential performance improvements. 
          Implementing these changes could significantly improve your site's performance.
        </p>
        
        <div class="table-container">
          <table class="table">
            <thead>
              <tr>
                <th>Opportunity</th>
                <th>Affected Pages</th>
                <th>Potential Savings</th>
                <th>Implementation</th>
              </tr>
            </thead>
            <tbody>
              ${this.generateOpportunityRows(allOpportunities)}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>`;
  }

  /**
   * Generate footer
   */
  private generateFooter(data: ProcessedAuditData): string {
    return `
  <footer style="background: var(--surface-color); border-top: 1px solid var(--border-color); padding: 2rem 0; margin-top: 4rem;">
    <div class="container">
      <div style="text-align: center; color: var(--text-secondary);">
        <p>Generated by <strong>Signaler</strong> v1.0.12</p>
        <p style="font-size: 0.875rem; margin-top: 0.5rem;">
          Report generated in ${Math.round(data.auditMetadata.elapsedMs / 1000)} seconds
        </p>
      </div>
    </div>
  </footer>`;
  }

  /**
   * Generate JavaScript for interactivity
   */
  private generateScripts(): string {
    return `
  <script>
    // Chart data and initialization
    const chartData = ${JSON.stringify(this.generateChartData())};
    
    // Initialize charts when DOM is loaded
    document.addEventListener('DOMContentLoaded', function() {
      initializeCharts();
      initializeFilters();
      initializeSorting();
    });
    
    function initializeCharts() {
      // Performance Score Distribution Chart
      const scoreCtx = document.getElementById('scoreDistributionChart');
      if (scoreCtx) {
        new Chart(scoreCtx, {
          type: 'doughnut',
          data: chartData.scoreDistribution,
          options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
              legend: {
                position: 'bottom'
              }
            }
          }
        });
      }
      
      // Issues Severity Chart
      const issuesCtx = document.getElementById('issuesSeverityChart');
      if (issuesCtx) {
        new Chart(issuesCtx, {
          type: 'bar',
          data: chartData.issuesSeverity,
          options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
              y: {
                beginAtZero: true
              }
            }
          }
        });
      }
      
      // Metrics Comparison Chart
      const metricsCtx = document.getElementById('metricsComparisonChart');
      if (metricsCtx) {
        new Chart(metricsCtx, {
          type: 'radar',
          data: chartData.metricsComparison,
          options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
              r: {
                beginAtZero: true,
                max: 100
              }
            }
          }
        });
      }
      
      // Opportunities Chart
      const oppCtx = document.getElementById('opportunitiesChart');
      if (oppCtx) {
        new Chart(oppCtx, {
          type: 'horizontalBar',
          data: chartData.opportunities,
          options: {
            responsive: true,
            maintainAspectRatio: false,
            indexAxis: 'y'
          }
        });
      }
    }
    
    function initializeFilters() {
      // Page filters
      const scoreFilter = document.getElementById('scoreFilter');
      const deviceFilter = document.getElementById('deviceFilter');
      const pageSearch = document.getElementById('pageSearch');
      
      if (scoreFilter) scoreFilter.addEventListener('change', filterPages);
      if (deviceFilter) deviceFilter.addEventListener('change', filterPages);
      if (pageSearch) pageSearch.addEventListener('input', filterPages);
      
      // Issue filters
      const severityFilter = document.getElementById('severityFilter');
      const categoryFilter = document.getElementById('categoryFilter');
      
      if (severityFilter) severityFilter.addEventListener('change', filterIssues);
      if (categoryFilter) categoryFilter.addEventListener('change', filterIssues);
    }
    
    function initializeSorting() {
      const sortableHeaders = document.querySelectorAll('.sortable');
      sortableHeaders.forEach(header => {
        header.style.cursor = 'pointer';
        header.addEventListener('click', () => sortTable(header.dataset.sort));
      });
    }
    
    function filterPages() {
      const scoreFilter = document.getElementById('scoreFilter')?.value;
      const deviceFilter = document.getElementById('deviceFilter')?.value;
      const searchTerm = document.getElementById('pageSearch')?.value.toLowerCase();
      
      const rows = document.querySelectorAll('#pagesTable tbody tr');
      
      rows.forEach(row => {
        let show = true;
        
        // Score filter
        if (scoreFilter) {
          const [min, max] = scoreFilter.split('-').map(Number);
          const performance = parseInt(row.dataset.performance);
          if (performance < min || performance > max) show = false;
        }
        
        // Device filter
        if (deviceFilter && row.dataset.device !== deviceFilter) {
          show = false;
        }
        
        // Search filter
        if (searchTerm) {
          const label = row.dataset.label;
          const path = row.dataset.path;
          if (!label.includes(searchTerm) && !path.includes(searchTerm)) {
            show = false;
          }
        }
        
        row.style.display = show ? '' : 'none';
      });
    }
    
    function filterIssues() {
      const severityFilter = document.getElementById('severityFilter')?.value;
      const categoryFilter = document.getElementById('categoryFilter')?.value;
      
      const issues = document.querySelectorAll('.issue-item');
      
      issues.forEach(issue => {
        let show = true;
        
        if (severityFilter && !issue.classList.contains(severityFilter)) {
          show = false;
        }
        
        if (categoryFilter && !issue.dataset.category === categoryFilter) {
          show = false;
        }
        
        issue.style.display = show ? '' : 'none';
      });
    }
    
    function sortTable(column) {
      const table = document.getElementById('pagesTable');
      const tbody = table.querySelector('tbody');
      const rows = Array.from(tbody.querySelectorAll('tr'));
      
      rows.sort((a, b) => {
        let aVal, bVal;
        
        if (column === 'label') {
          aVal = a.dataset.label;
          bVal = b.dataset.label;
          return aVal.localeCompare(bVal);
        } else {
          aVal = parseInt(a.dataset[column]) || 0;
          bVal = parseInt(b.dataset[column]) || 0;
          return bVal - aVal; // Descending order for scores
        }
      });
      
      rows.forEach(row => tbody.appendChild(row));
    }
    
    function clearFilters() {
      document.getElementById('scoreFilter').value = '';
      document.getElementById('deviceFilter').value = '';
      document.getElementById('pageSearch').value = '';
      document.getElementById('severityFilter').value = '';
      document.getElementById('categoryFilter').value = '';
      
      filterPages();
      filterIssues();
    }
    
    // Smooth scrolling for navigation
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
        e.preventDefault();
        const target = document.querySelector(this.getAttribute('href'));
        if (target) {
          target.scrollIntoView({
            behavior: 'smooth',
            block: 'start'
          });
        }
      });
    });
  </script>`;
  }

  /**
   * Helper methods
   */
  private getScoreClass(score: number): string {
    if (score >= 90) return 'score-excellent';
    if (score >= 75) return 'score-good';
    if (score >= 50) return 'score-needs-improvement';
    return 'score-poor';
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  private groupIssuesByType(issues: any[]): Record<string, any[]> {
    return issues.reduce((groups, issue) => {
      const type = issue.id;
      if (!groups[type]) groups[type] = [];
      groups[type].push(issue);
      return groups;
    }, {});
  }

  private generateIssueGroup(type: string, issues: any[]): string {
    const firstIssue = issues[0];
    const affectedPages = [...new Set(issues.map(issue => issue.pageLabel))];
    
    return `
    <div class="card issue-item ${firstIssue.severity}" data-category="${firstIssue.category}">
      <div class="issue-header">
        <h3 class="issue-title">${this.escapeHtml(firstIssue.title)}</h3>
        <span class="severity severity-${firstIssue.severity}">${firstIssue.severity}</span>
      </div>
      
      <p style="margin-bottom: 1rem; color: var(--text-secondary);">
        ${this.escapeHtml(firstIssue.description)}
      </p>
      
      <div style="margin-bottom: 1rem;">
        <strong>Affected Pages:</strong> ${affectedPages.length} 
        (${affectedPages.slice(0, 3).join(', ')}${affectedPages.length > 3 ? '...' : ''})
      </div>
      
      <div class="issue-savings">
        <strong>Potential Savings:</strong> 
        ${Math.round(issues.reduce((sum, issue) => sum + issue.estimatedSavings.timeMs, 0) / 1000)}s total
      </div>
      
      ${firstIssue.fixRecommendations.length > 0 ? `
        <div style="margin-top: 1rem;">
          <strong>Recommended Fix:</strong>
          <p>${this.escapeHtml(firstIssue.fixRecommendations[0].action)}</p>
          ${firstIssue.fixRecommendations[0].implementation.codeExample ? `
            <div class="code-example">${this.escapeHtml(firstIssue.fixRecommendations[0].implementation.codeExample)}</div>
          ` : ''}
          <div style="font-size: 0.875rem; color: var(--text-secondary);">
            Difficulty: ${firstIssue.fixRecommendations[0].implementation.difficulty} • 
            Estimated time: ${firstIssue.fixRecommendations[0].implementation.estimatedTime}
          </div>
        </div>
      ` : ''}
    </div>`;
  }

  private generateOpportunityRows(opportunities: any[]): string {
    const grouped = this.groupOpportunitiesByType(opportunities);
    
    return Object.entries(grouped).map(([type, opps]) => {
      const totalSavings = opps.reduce((sum, opp) => sum + opp.estimatedSavings.timeMs, 0);
      const affectedPages = [...new Set(opps.map(opp => opp.pageLabel))];
      
      return `
      <tr>
        <td>
          <div style="font-weight: 600;">${this.escapeHtml(opps[0].title)}</div>
          <div style="font-size: 0.875rem; color: var(--text-secondary);">
            ${this.escapeHtml(opps[0].description)}
          </div>
        </td>
        <td>${affectedPages.length} pages</td>
        <td>
          <strong>${Math.round(totalSavings / 1000)}s</strong>
        </td>
        <td>
          <span class="severity severity-medium">Medium</span>
        </td>
      </tr>`;
    }).join('');
  }

  private groupOpportunitiesByType(opportunities: any[]): Record<string, any[]> {
    return opportunities.reduce((groups, opp) => {
      const type = opp.id;
      if (!groups[type]) groups[type] = [];
      groups[type].push(opp);
      return groups;
    }, {});
  }

  private generateChartData(): any {
    // This would be populated with actual data in a real implementation
    return {
      scoreDistribution: {
        labels: ['Excellent (90-100)', 'Good (75-89)', 'Needs Improvement (50-74)', 'Poor (0-49)'],
        datasets: [{
          data: [25, 35, 30, 10],
          backgroundColor: ['#16a34a', '#22c55e', '#d97706', '#dc2626']
        }]
      },
      issuesSeverity: {
        labels: ['Critical', 'High', 'Medium', 'Low'],
        datasets: [{
          label: 'Number of Issues',
          data: [5, 12, 18, 8],
          backgroundColor: ['#991b1b', '#dc2626', '#d97706', '#16a34a']
        }]
      },
      metricsComparison: {
        labels: ['Performance', 'Accessibility', 'Best Practices', 'SEO'],
        datasets: [{
          label: 'Average Scores',
          data: [65, 85, 78, 92],
          backgroundColor: 'rgba(37, 99, 235, 0.2)',
          borderColor: '#2563eb'
        }]
      },
      opportunities: {
        labels: ['Unused JavaScript', 'Image Optimization', 'Text Compression', 'Modern Image Formats'],
        datasets: [{
          label: 'Potential Savings (seconds)',
          data: [2.5, 1.8, 1.2, 0.9],
          backgroundColor: '#2563eb'
        }]
      }
    };
  }
}