#!/usr/bin/env bash
set -euo pipefail
CLI_NAME="signaler"
PKG_VER="$(node -p "require('./package.json').version")"
ZIP_BASENAME="${CLI_NAME}-${PKG_VER}-portable"
ZIP_DIR="release/${ZIP_BASENAME}"
mkdir -p "${ZIP_DIR}"
cp -R dist "${ZIP_DIR}/dist"
mkdir -p "${ZIP_DIR}/release-assets"
cp release-assets/run.sh "${ZIP_DIR}/release-assets/run.sh"
cp release-assets/run.cmd "${ZIP_DIR}/release-assets/run.cmd"
cp release-assets/signaler.sh "${ZIP_DIR}/release-assets/signaler.sh"
cp release-assets/signaler.cmd "${ZIP_DIR}/release-assets/signaler.cmd"
cp release-assets/install.sh "${ZIP_DIR}/release-assets/install.sh"
cp release-assets/install.ps1 "${ZIP_DIR}/release-assets/install.ps1"
cp package.json "${ZIP_DIR}/package.json"
cp README.md "${ZIP_DIR}/README.md"
cp LICENSE "${ZIP_DIR}/LICENSE"
chmod +x "${ZIP_DIR}/release-assets/run.sh"
chmod +x "${ZIP_DIR}/release-assets/signaler.sh"
chmod +x "${ZIP_DIR}/release-assets/install.sh"
(cd release && zip -r "${ZIP_BASENAME}.zip" "${ZIP_BASENAME}")
