#!/usr/bin/env node

/**
 * Post-install script to create cross-platform CLI wrappers
 * This ensures the CLI works in both PowerShell/CMD and Git Bash/Unix shells
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { writeFileSync, chmodSync, existsSync, mkdirSync } from 'node:fs';
import { platform } from 'node:os';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Determine if we're in a global installation
const isGlobalInstall = process.env.npm_config_global === 'true' || 
                        process.argv.includes('-g') || 
                        process.argv.includes('--global');

// Get the bin directory based on installation type
function getBinDir() {
  if (isGlobalInstall) {
    // Global installation - use npm's global bin directory
    const npmPrefix = process.env.npm_config_prefix || 
                     (platform() === 'win32' 
                       ? join(process.env.APPDATA || '', 'npm')
                       : '/usr/local');
    return join(npmPrefix, 'bin');
  } else {
    // Local installation - use node_modules/.bin
    return join(process.cwd(), 'node_modules', '.bin');
  }
}

// Get the path to the actual CLI script
function getCliPath() {
  // Try to find the dist/bin.js relative to this script
  const localPath = join(__dirname, '..', 'dist', 'bin.js');
  if (existsSync(localPath)) {
    return localPath;
  }
  
  // Fallback: assume we're in node_modules
  const nodeModulesPath = join(__dirname, '..', '..', '@signaler', 'cli', 'dist', 'bin.js');
  if (existsSync(nodeModulesPath)) {
    return nodeModulesPath;
  }
  
  // Last resort: use relative path
  return join(__dirname, '..', 'dist', 'bin.js');
}

function createBashWrapper(binDir, cliPath) {
  const wrapperPath = join(binDir, 'signaler');
  const wrapperContent = `#!/usr/bin/env bash
# Signaler CLI wrapper for Unix/Git Bash
# Auto-generated by postinstall script

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

# Find the actual CLI script
CLI_PATH="${cliPath}"

# If the path doesn't exist, try to find it relative to this script
if [ ! -f "$CLI_PATH" ]; then
  # Try node_modules path
  CLI_PATH="$SCRIPT_DIR/../lib/node_modules/@signaler/cli/dist/bin.js"
fi

if [ ! -f "$CLI_PATH" ]; then
  # Try local installation
  CLI_PATH="$SCRIPT_DIR/../node_modules/@signaler/cli/dist/bin.js"
fi

if [ ! -f "$CLI_PATH" ]; then
  echo "Error: Could not find signaler CLI script"
  echo "Tried: ${cliPath}"
  exit 1
fi

# Execute the CLI with Node.js
exec node "$CLI_PATH" "$@"
`;

  try {
    // Create bin directory if it doesn't exist
    if (!existsSync(binDir)) {
      mkdirSync(binDir, { recursive: true });
    }

    // Write the wrapper script
    writeFileSync(wrapperPath, wrapperContent, { mode: 0o755 });
    
    // Make it executable (Unix/Mac)
    if (platform() !== 'win32') {
      try {
        chmodSync(wrapperPath, 0o755);
      } catch (err) {
        console.warn('Warning: Could not make wrapper executable:', err.message);
      }
    }

    console.log('✓ Created Bash wrapper:', wrapperPath);
    return true;
  } catch (err) {
    console.error('Error creating Bash wrapper:', err.message);
    return false;
  }
}

function createWindowsWrapper(binDir, cliPath) {
  const wrapperPath = join(binDir, 'signaler.cmd');
  const wrapperContent = `@echo off
REM Signaler CLI wrapper for Windows
REM Auto-generated by postinstall script

node "${cliPath}" %*
`;

  try {
    // Create bin directory if it doesn't exist
    if (!existsSync(binDir)) {
      mkdirSync(binDir, { recursive: true });
    }

    // Write the wrapper script
    writeFileSync(wrapperPath, wrapperContent);
    
    console.log('✓ Created Windows wrapper:', wrapperPath);
    return true;
  } catch (err) {
    console.error('Error creating Windows wrapper:', err.message);
    return false;
  }
}

function main() {
  console.log('Setting up Signaler CLI wrappers...');
  
  const binDir = getBinDir();
  const cliPath = getCliPath();
  
  console.log('Bin directory:', binDir);
  console.log('CLI path:', cliPath);
  console.log('Platform:', platform());
  console.log('Global install:', isGlobalInstall);
  
  // Verify CLI exists
  if (!existsSync(cliPath)) {
    console.warn('Warning: CLI script not found at:', cliPath);
    console.warn('Wrappers may not work correctly until the package is built');
  }
  
  let success = true;
  
  // Create Bash wrapper (for Unix/Mac/Git Bash)
  if (!createBashWrapper(binDir, cliPath)) {
    success = false;
  }
  
  // Create Windows wrapper (for CMD/PowerShell)
  if (platform() === 'win32') {
    if (!createWindowsWrapper(binDir, cliPath)) {
      success = false;
    }
  }
  
  if (success) {
    console.log('\n✓ Signaler CLI is ready to use!');
    console.log('\nUsage:');
    console.log('  signaler wizard');
    console.log('  signaler audit');
    console.log('\nThe CLI now works in:');
    console.log('  - Git Bash');
    console.log('  - PowerShell');
    console.log('  - CMD');
    console.log('  - Unix/Mac terminals');
  } else {
    console.error('\n✗ Some wrappers failed to create');
    console.error('You may need to run the CLI directly with: node', cliPath);
  }
}

main();
