#!/usr/bin/env bash
# Setup script to create a bash wrapper for Signaler CLI
# This enables the CLI to work in Git Bash on Windows

set -e

echo "Setting up Signaler CLI for Git Bash..."

# Detect the installation directory
if [ -d "$HOME/AppData/Local/signaler/bin" ]; then
    BIN_DIR="$HOME/AppData/Local/signaler/bin"
elif [ -d "/c/Users/$USER/AppData/Local/signaler/bin" ]; then
    BIN_DIR="/c/Users/$USER/AppData/Local/signaler/bin"
elif [ -d "C:/Users/$USER/AppData/Local/signaler/bin" ]; then
    BIN_DIR="C:/Users/$USER/AppData/Local/signaler/bin"
else
    echo "Error: Could not find Signaler installation directory"
    echo "Please ensure Signaler is installed via: npx jsr add @signaler/cli"
    exit 1
fi

echo "Found installation at: $BIN_DIR"

# Find the signaler root directory
if [ -d "$HOME/AppData/Local/signaler/current" ]; then
    SIGNALER_ROOT="$HOME/AppData/Local/signaler/current"
elif [ -d "/c/Users/$USER/AppData/Local/signaler/current" ]; then
    SIGNALER_ROOT="/c/Users/$USER/AppData/Local/signaler/current"
elif [ -d "C:/Users/$USER/AppData/Local/signaler/current" ]; then
    SIGNALER_ROOT="C:/Users/$USER/AppData/Local/signaler/current"
else
    echo "Error: Could not find Signaler root directory"
    exit 1
fi

echo "Signaler root: $SIGNALER_ROOT"

# Create the bash wrapper
WRAPPER_PATH="$BIN_DIR/signaler"

cat > "$WRAPPER_PATH" << 'WRAPPER_EOF'
#!/usr/bin/env bash
# Signaler CLI wrapper for Git Bash/Unix
# Auto-generated by setup-bash-wrapper.sh

# Detect the Signaler root directory
if [ -d "$HOME/AppData/Local/signaler/current" ]; then
    SIGNALER_ROOT="$HOME/AppData/Local/signaler/current"
elif [ -d "/c/Users/$USER/AppData/Local/signaler/current" ]; then
    SIGNALER_ROOT="/c/Users/$USER/AppData/Local/signaler/current"
elif [ -d "C:/Users/$USER/AppData/Local/signaler/current" ]; then
    SIGNALER_ROOT="C:/Users/$USER/AppData/Local/signaler/current"
else
    echo "Error: Could not find Signaler installation"
    exit 1
fi

# Execute the CLI with Node.js
exec node "$SIGNALER_ROOT/dist/bin.js" "$@"
WRAPPER_EOF

# Make it executable
chmod +x "$WRAPPER_PATH"

echo ""
echo "✓ Bash wrapper created successfully!"
echo ""
echo "You can now use Signaler in Git Bash:"
echo "  signaler wizard"
echo "  signaler audit"
echo ""
echo "The wrapper is located at: $WRAPPER_PATH"
