#!/usr/bin/env pwsh
# Setup script to create a bash wrapper for Signaler CLI
# This enables the CLI to work in Git Bash on Windows

Write-Host "Setting up Signaler CLI for Git Bash..." -ForegroundColor Cyan
Write-Host ""

# Detect the installation directory
$BinDir = "$env:LOCALAPPDATA\signaler\bin"
$SignalerRoot = "$env:LOCALAPPDATA\signaler\current"

if (-not (Test-Path $BinDir)) {
    Write-Host "Error: Could not find Signaler installation directory" -ForegroundColor Red
    Write-Host "Expected: $BinDir" -ForegroundColor Gray
    Write-Host "Please ensure Signaler is installed via: npx jsr add @signaler/cli" -ForegroundColor Yellow
    exit 1
}

Write-Host "Found installation at: $BinDir" -ForegroundColor Green

if (-not (Test-Path $SignalerRoot)) {
    Write-Host "Error: Could not find Signaler root directory" -ForegroundColor Red
    Write-Host "Expected: $SignalerRoot" -ForegroundColor Gray
    exit 1
}

Write-Host "Signaler root: $SignalerRoot" -ForegroundColor Green
Write-Host ""

# Create the bash wrapper
$WrapperPath = Join-Path $BinDir "signaler"

$WrapperContent = @'
#!/usr/bin/env bash
# Signaler CLI wrapper for Git Bash/Unix
# Auto-generated by setup-bash-wrapper.ps1

# Detect the Signaler root directory
if [ -d "$HOME/AppData/Local/signaler/current" ]; then
    SIGNALER_ROOT="$HOME/AppData/Local/signaler/current"
elif [ -d "/c/Users/$USER/AppData/Local/signaler/current" ]; then
    SIGNALER_ROOT="/c/Users/$USER/AppData/Local/signaler/current"
elif [ -d "C:/Users/$USER/AppData/Local/signaler/current" ]; then
    SIGNALER_ROOT="C:/Users/$USER/AppData/Local/signaler/current"
else
    echo "Error: Could not find Signaler installation"
    exit 1
fi

# Execute the CLI with Node.js
exec node "$SIGNALER_ROOT/dist/bin.js" "$@"
'@

try {
    Set-Content -Path $WrapperPath -Value $WrapperContent -NoNewline
    Write-Host "✓ Bash wrapper created successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "You can now use Signaler in Git Bash:" -ForegroundColor Cyan
    Write-Host "  signaler wizard" -ForegroundColor White
    Write-Host "  signaler audit" -ForegroundColor White
    Write-Host ""
    Write-Host "The wrapper is located at: $WrapperPath" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Note: You may need to restart Git Bash for the changes to take effect." -ForegroundColor Yellow
} catch {
    Write-Host "Error creating wrapper: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}
